# Generated by Django 4.2.17 on 2026-01-15 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASLSign',
            fields=[
                ('letter', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('hand_shape', models.CharField(max_length=50)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asl_signs',
                'ordering': ['letter'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('hand_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('dominant_hand', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('total_gestures', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('session_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GestureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_context', models.CharField(default='general', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('gesture_count', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gestures.userprofile')),
            ],
            options={
                'db_table': 'gesture_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GestureData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_sign', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('recognition_method', models.CharField(default='fingerpose', max_length=50)),
                ('landmarks', models.JSONField(blank=True, null=True)),
                ('hand_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_low_confidence', models.BooleanField(default=False)),
                ('recognition_failed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestures', to='gestures.gesturesession')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestures', to='gestures.userprofile')),
            ],
            options={
                'db_table': 'gesture_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_profile', 'detected_sign'], name='gesture_dat_user_pr_e81d50_idx'), models.Index(fields=['timestamp'], name='gesture_dat_timesta_d4b793_idx')],
            },
        ),
        migrations.CreateModel(
            name='GestureAccuracy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gesture_sign', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('personalized_threshold', models.FloatField(default=0.8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracies', to='gestures.userprofile')),
            ],
            options={
                'db_table': 'gesture_accuracy',
                'ordering': ['-successful'],
                'unique_together': {('user_profile', 'gesture_sign')},
            },
        ),
    ]
